# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b1b95101699078dca8f677a84da62de27cdc5af28e7e11d5d6dbfe1a88340e80ec156a04378934f4f7aa247d57deccfc20f54c9ae4f933ca7857d37c5c363df

test:
  secret_key_base: 7ba1586e2da279836d216640c01a3a94a7c468838a1ad46ccbe86cd919de7e0372309e12e3ef1134d85c37641369db144538956913acbeb168ea523452860560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
